(function (root, factory) {
  const data = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = data;
  }
  root.CV_CONTENT_EN = data;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  return {
    contact: "Contact",
    phone: "Phone",
    email: "Email",
    address: "Address",
    github: "GitHub",
    linkedin: "LinkedIn",
    languages: "Languages",
    spanish: "Spanish",
    native: "Native",
    english: "English",
    englishLevel: "Upper-Intermediate (B2+)",
    french: "French",
    basic: "Basic",
    jobTitle: "Systems <span>Engineer</span>",
    profile: "Profile",
    profileText1: "Senior Software Engineer and Full Stack Developer with <strong>12+ years of experience</strong> delivering <strong>robust, scalable products</strong> across complex domains.",
    profileText2: "Specializing in <strong>frontend architecture with full-stack depth</strong>, I design and implement sophisticated systems — from <strong>graph-based routing</strong> and <strong>real-time data pipelines</strong> to <strong>AWS microservices</strong> and <strong>WebGL 3D rendering</strong> — while owning architectural decisions and leading cross-functional teams.",
    profileText3: "I combine a <strong>pragmatic, product-focused mindset</strong> with hands-on execution and modern <strong>AI-assisted development workflows</strong> to ship maintainable, high-quality solutions efficiently.",
    experience: "Experience",
    companyName: "3D Virtual Environment Solutions",
    companySector: "Construction Technology Sector",
    companyRole: "Innovation Engineering",
    companySummary: "Progressed through five roles over 11+ years at a single employer — <strong>Software Developer</strong> (2015-2016), <strong>Frontend Developer</strong> (2016-2018), <strong>Full Stack Developer</strong> (2018-2023), <strong>Software Engineer</strong> (2023-2024) and <strong>Software Architect</strong> (2024-2026) — growing from frontend engineer to <strong>technical lead</strong>. Built deep expertise across the full stack: <strong>frontend architecture with React and TypeScript</strong>, algorithm design, <strong>cloud infrastructure on AWS</strong>, 3D and AR experiences, and microservices, owning <strong>architecture decisions</strong>, team coordination and end-to-end delivery.",
    vEyeTitle: "vEye - Hospital Digital Twin",
    vEyeMeta: "Software Developer · 2015 – 2016",
    vEye1: "Contributed to the architecture of a hospital-scale <strong>digital twin</strong> using <strong>Unity 3D</strong> and a MENU stack (MongoDB, Express, Node.js, Unity), integrating <strong>live HVAC sensor data</strong> across a multi-building complex for a US client.",
    vEye2: "Designed <strong>OOP-based C#/.NET controller abstractions</strong> in Unity to manage interactive 3D elements, enabling polymorphic behavior per equipment type.",
    vEye3: "Built the <strong>HUD layer and interfaces</strong> to visualize sensor data and let operators update equipment state in real time, with filters rendering <strong>500+ assets simultaneously at 60 FPS</strong>.",
    resourceTitle: "Resource Distribution Tool",
    resourceMeta: "Frontend Developer · 2016 – 2018",
    resource1: "Developed the frontend of a <strong>construction resource planning web app</strong> using <strong>React, Chart.js and MongoDB</strong>, enabling percentage-based resource allocation across time via interactive calendar and breakdown views.",
    resource2: "Replaced legacy <strong>jQuery</strong> components with <strong>React</strong>, reducing frontend complexity and boosting maintainability and performance by <strong>~50%</strong>.",
    hololensTitle: "HoloLens AR Prototype",
    hololensMeta: "Full Stack Developer · 2018 – 2023",
    hololens1: "Designed and implemented an <strong>AR application using the Microsoft HoloLens SDK and Unity</strong>, streaming 3D assets from a file server to stay within device memory constraints, which required deep optimization of model geometry.",
    arasTitle: "ARAS / BIMEP - HVAC Automation Platform (Core Project)",
    arasMeta: "Full Stack Developer · 2018 – 2023",
    aras1: "Led the migration from a vanilla JS monolith to a <strong>React, TypeScript and Node.js</strong> architecture, establishing component reuse patterns that <strong>cut web-component management time by ~90%</strong> and reducing runtime errors through static typing.",
    aras2: "Designed and implemented a <strong>Dijkstra-based pipe auto-routing algorithm</strong> using a room-grid graph where edge weights encode HVAC heat load, automating layout-aware pipe distribution across building floors.",
    aras3: "Authored <strong>Revit plugins in C#</strong> to extend the platform directly inside the mechanical designer's workflow, bridging the web application with BIM tooling.",
    aras4: "Architected the transition to a <strong>microservices model on AWS</strong> (ECS Fargate, EC2, API Gateway, CloudWatch, load balancers), decomposing compute-intensive algorithms into independently scalable services.",
    aras5: "Built a <strong>lightweight custom message broker</strong> to coordinate asynchronous communication between Node.js services and AWS Lambda functions running Python-based algorithms for clean room detection, zoning, equipment plotting and ductwork generation.",
    aras6: "Served as <strong>technical lead</strong> during the algorithm integration phase: owned infrastructure and architecture decisions, ran planning sessions, managed the backlog in Notion and coordinated a cross-functional team across engineering, design and data science.",
    aras7: "Used local Kubernetes environments for development and integration testing to avoid AWS costs, and established <strong>CI/CD pipelines via GitHub Actions</strong> with semantic versioning and conventional commits.",
    takeoffTitle: "Virtual Takeoff - Facility Mapping Tool",
    takeoffMeta: "Software Engineer · 2023 – 2024",
    takeoff1: "Led end-to-end delivery of a <strong>facility mapping application</strong> (React, Next.js, PostgreSQL, MongoDB, Mapbox) allowing users to annotate floor plans with <strong>geolocated markers</strong> enriched with images, audio, video and notes.",
    takeoff2: "Owned <strong>project management</strong> for the initiative: scheduling, task assignment and deliverable coordination alongside a small engineering team.",
    catalogueTitle: "Commercial Catalogue",
    catalogueMeta: "Full Stack Developer · 2018 – 2023",
    catalogue1: "Built a <strong>Next.js and PostgreSQL</strong> HVAC equipment catalogue with advanced filtering, deployed on AWS, reducing quote preparation time for contractor users.",
    viewerTitle: "3D Model Viewer - Browser-Native Pipeline",
    viewerMeta: "Software Architect · 2024 – 2026",
    viewer1: "Designed and implemented a <strong>file conversion pipeline</strong> (Revit RVT and LAS to XKT) with a server-side processing queue and <strong>WebSocket-based progress notifications</strong>, enabling teams to load BIM models in the browser without login friction.",
    viewer2: "Integrated <strong>interactive viewer tools</strong> (measurements, camera controls, model transforms) and owned full-stack delivery from the conversion backend to frontend rendering, <strong>cutting model load time by ~50%</strong> and supporting <strong>100 concurrent users</strong> through the optimized conversion and streaming pipeline; used <strong>AI-assisted development</strong> to improve delivery efficiency by ~80%.",
    technicalSkills: "Technical Skills",
    advanced: "Advanced",
    intermediate: "Intermediate",
    programming: "Programming",
    frameworksTools: "Frameworks / Tools",
    databases: "Databases",
    softSkills: "Soft Skills",
    skill1: "Self-management & Proactivity",
    skill2: "Assertive Communication",
    skill3: "Solution-oriented Thinking",
    skill4: "Curiosity & Innovation Mindset",
    skill5: "Continuous Learning",
    skill6: "Leadership & Team Guidance",
    careerObjective: "Career Objective",
    careerObjectiveText: "To secure a <strong>Software Architect | Principal Software Engineer</strong> role in an international company (remote, hybrid or on-site) where I can contribute to systems, architectures and high-impact products, while continuing to grow toward principal or architect-level responsibilities in global engineering teams.",
    education: "Education",
    universityEducation: "University Education",
    systemsEngineering: "Bachelor of Engineering (BEng), Systems Engineering",
    educationDescription: "Professional engineering degree. Coursework spanned software engineering, data structures and algorithms, databases, operating systems, computer networks, and systems analysis and design, on a strong mathematics foundation, with an emphasis on designing and building software systems end to end.",
    universityName: "Universidad Distrital Francisco Jose de Caldas",
    complementaryTraining: "Complementary Training",
    unityCertified: "Unity Certified Developer",
    conferences: "Conferences",
    atsButton: "ATS",
    githubCopilot: "Github copilot as AI agent",
    testing: "playwright, cypress - testing",
    devops: "DevOps, CI/CD, containers (Docker, Kubernetes)"
  };
});
